apiVersion: v1
kind: Service
metadata:
  name: hello-telemetry
  labels:
    app: hello-telemetry
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-telemetry
